CREATE TABLE pessoas(
	ID_PESSOA SERIAL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL, 
	DATA_NASCIMENTO DATE NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	RG VARCHAR(15) NOT NULL UNIQUE,
	TELEFONE VARCHAR(11),
	ESTADO_CIVIL VARCHAR(255) NOT NULL,
	PROFISSAO VARCHAR(255)

);

CREATE TABLE imovel(
	ID_IMOVEL SERIAL PRIMARY KEY,
    TIPO_IMOVEL VARCHAR(255) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    COMPLEMENTO VARCHAR(50) NOT NULL,
  	CEP VARCHAR(10) NOT NULL,
	CIDADE VARCHAR (255) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL,
    ID_PESSOA INTEGER,
    FOREIGN KEY (ID_PESSOA) 
		REFERENCES pessoas(ID_PESSOA)
    	ON UPDATE CASCADE ON DELETE CASCADE,
    ADQUIRIDO_EM DATE NOT NULL
);

CREATE TABLE bancos(
	ID_BANCO SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE clientes(
	ID_CLIENTE SERIAL PRIMARY KEY, 
	ID_PESSOA INT NOT NULL,
	FOREIGN KEY (ID_PESSOA)
		REFERENCES pessoas(ID_PESSOA)
		ON UPDATE CASCADE ON DELETE CASCADE,
	ENDERECO VARCHAR(255) NOT NULL,
    COMPLEMENTO VARCHAR(50) NOT NULL,
  	CEP VARCHAR(10) NOT NULL,
	CIDADE VARCHAR (255) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL,
	ID_BANCO INT NOT NULL,
	FOREIGN KEY (ID_BANCO) 
		REFERENCES bancos(ID_BANCO)
		ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE COMPRAS(
	ID_COMPRAS SERIAL PRIMARY KEY, 	
	ID_IMOVEL INT NOT NULL,
	FOREIGN KEY (ID_IMOVEL)
		REFERENCES imovel(ID_IMOVEL)
		ON UPDATE CASCADE ON DELETE CASCADE,
	ID_CLIENTE INT NOT NULL,
	FOREIGN KEY (ID_CLIENTE)
		REFERENCES clientes(ID_CLIENTE)
		ON UPDATE CASCADE ON DELETE CASCADE,
	DATA_COMPRA DATE NOT NULL, 
	TIPO_VENDA VARCHAR(100) NOT NULL,
	VALOR_IMOVEL DECIMAL NOT NULL, 
	VALOR_ENTRADA DECIMAL NOT NULL,
	PARCELAS INTEGER
);

CREATE TABLE despesas(
	ID_DESPESA SERIAL PRIMARY KEY, 
	ID_IMOVEL INT NOT NULL,
	ENERGIA DECIMAL,
	AGUA DECIMAL, 
	CONDOMINIO DECIMAL,
	PROPAGANDA DECIMALT,
	FOREIGN KEY (ID_IMOVEL)
		REFERENCES imovel(ID_IMOVEL)
);


